


ALL : 
	$(MAKE) -C c_examples
	$(MAKE) -C python_examples
	$(MAKE) -C julia_examples
	$(MAKE) -C rust_examples


clean : 
	$(MAKE) -C c_examples clean
	$(MAKE) -C python_examples clean
	$(MAKE) -C julia_examples clean
	$(MAKE) -C rust_examples clean
